[project]
name = "RestAPI"
version = "0.1.0"
description = "Restful API on FastAPI for ECommerce"
authors = ["coldman", "kostya12362"]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic==1.15.2",
    "asyncio==3.4.3",
    "asyncpg==0.30.0",
    "fastapi==0.115.12",
    "fastapi-cli==0.0.7",
    "greenlet==3.2.1",
    "loguru==0.7.3",
    "pydantic==2.11.4",
    "pydantic-settings==2.9.1",
    "python-multipart==0.0.20",
    "sqlalchemy==2.0.40",
    "typer==0.15.3",
    "uvicorn==0.34.2",
]

[dependency-groups]
dev = [
    "coverage==7.8.0",
    "httpx==0.28.1",
    "pytest==8.3.5",
    "pytest-asyncio==0.26.0",
    "pytest-mock==3.14.0",
    "black==25.1.0",
    "isort==6.0.1",
    "mypy==1.15.0",
    "ruff==0.11.8",
]

# ruff configuration
[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
line-length = 79
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".mypy_cache",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "__pycache_",
    "_build",
    "buck-out",
    "build",
    "dist",
    "venv",
    "Makefile",
    "migrations",
]

# iSort configuration
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
skip = '.venv,venv,env,anomaly_detector'
src_paths = ["src"]

# Black configuration
[tool.black]
target-version = ['py312']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | .venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
                     # the root of the project
)
'''
line-length = 79

# MyPy configuration
[tool.mypy]
plugins = [
    "pydantic.mypy"
]
python_version = '3.12'

# Add the 'src' directory to the module search path
mypy_path = ['src']

# Specify the directories to check
files = [
    'src',
    'tests',
]

warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
explicit_package_bases = true

exclude = [
    "migrations",
    "simulator",
    "anomaly_detector",
    "estimator",
]

# Suppress type import errors
follow_imports = 'silent'

[[tool.mypy.overrides]]
module = [
    "websockets.exceptions",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = [
    ".", "src",
]
addopts = '-s -v --cache-clear'
python_functions = 'test_* *_test'
asyncio_mode = "auto"
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"

[tool.coverage.run]
omit = [
    "*/conftest.py",
    "*/test_*.py",
    "*/migrations/",
]
