"""empty message

Revision ID: 47f3eaf54a67
Revises: 3e254d725aba
Create Date: 2025-07-30 15:40:35.252871

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "47f3eaf54a67"
down_revision: str | None = "082cdb59597f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    # ### end Alembic commands ###
