"""empty message

Revision ID: d85de8610cf6
Revises: 47f3eaf54a67
Create Date: 2025-12-10 23:38:54.363842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85de8610cf6'
down_revision: Union[str, None] = '47f3eaf54a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.create_index(op.f('ix_brands_brands_id'), 'brands', ['id'], unique=False)
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_constraint(op.f('uq_categories_name_level'), 'categories', type_='unique')
    op.drop_constraint(op.f('uq_categories_sort_order_level'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_unique_constraint(op.f('uq_categories_name'), 'categories', ['name', 'parent_id'])
    op.create_unique_constraint(op.f('uq_categories_sort_order'), 'categories', ['sort_order', 'parent_id'])
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.create_index(op.f('ix_countries_countries_id'), 'countries', ['id'], unique=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_constraint(op.f('products_isbn_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_products_id'), 'products', ['id'], unique=False)
    op.create_unique_constraint(op.f('uq_products_isbn'), 'products', ['isbn'])
    op.create_unique_constraint(op.f('uq_products_sku'), 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_products_sku'), 'products', type_='unique')
    op.drop_constraint(op.f('uq_products_isbn'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_products_id'), table_name='products')
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_isbn_key'), 'products', ['isbn'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_index(op.f('ix_countries_countries_id'), table_name='countries')
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.drop_constraint(op.f('uq_categories_sort_order'), 'categories', type_='unique')
    op.drop_constraint(op.f('uq_categories_name'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_categories_parent_id'), table_name='categories')
    op.create_unique_constraint(op.f('uq_categories_sort_order_level'), 'categories', ['sort_order', 'parent_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_categories_name_level'), 'categories', ['name', 'parent_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_brands_brands_id'), table_name='brands')
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    # ### end Alembic commands ###
