"""empty message

Revision ID: 63a107752874
Revises: 360c3bb895a4
Create Date: 2024-09-17 21:48:50.397005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a107752874'
down_revision: Union[str, None] = '360c3bb895a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
