"""empty message

Revision ID: 00132cebbc53
Revises: 25379fc929c5
Create Date: 2024-09-22 03:15:17.980153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00132cebbc53'
down_revision: Union[str, None] = '25379fc929c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_name', sa.String(), nullable=False))
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('countries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('countries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('products', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'created_by',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'updated_by',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               nullable=True)
    op.drop_index('ix_products_id', table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.alter_column('products', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('countries', 'updated_at')
    op.drop_column('countries', 'created_at')
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('categories', 'category_name')
    # ### end Alembic commands ###
